import { getSupabaseServer } from './supabase';
export type ServiceRequest = { id:string; producer_name:string; producer_whatsapp:string; company_name?:string|null; country?:string; state?:string|null; city?:string|null; service_type:string; crop?:string|null; area_amount?:number|null; area_unit?:string|null; expected_start_date?:string|null; urgency?:string|null; approximate_location?:string|null; notes?:string|null; status:string; estimated_value?:number|null; created_at?:string; provider_interests?: { id:string }[] };
export type Provider = { id:string; name:string; company_name?:string|null; whatsapp:string; state?:string|null; city?:string|null; service_radius_km?:number|null; provider_type?:string|null; source?:string|null; status:string; machines?: Machine[]; created_at?:string };
export type Machine = { id:string; provider_id?:string; machine_type:string; brand?:string|null; model?:string|null; year?:number|null; platform_width?:string|null; supported_crops?:string[]; available_from?:string|null; available_until?:string|null; base_city?:string|null; base_state?:string|null; service_radius_km?:number|null; average_price?:number|null; status:string; is_featured?:boolean; service_providers?: Provider };
export const sampleRequests: ServiceRequest[] = [{id:'demo-1', producer_name:'Fazenda Boa Safra', producer_whatsapp:'5564999999999', city:'Rio Verde', state:'GO', service_type:'colheita', crop:'soja', area_amount:420, area_unit:'ha', expected_start_date:'2026-02-10', urgency:'alta', status:'novo', estimated_value:85000, provider_interests:[{id:'i1'}]}, {id:'demo-2', producer_name:'Agro Cerrado', producer_whatsapp:'5562999999999', city:'Jataí', state:'GO', service_type:'pulverização', crop:'milho', area_amount:180, area_unit:'ha', expected_start_date:'2026-03-05', urgency:'normal', status:'em_negociacao', estimated_value:22000, provider_interests:[]}];
export const sampleProviders: Provider[] = [{id:'prov-1', name:'Máquinas Rio Verde', company_name:'MRV Serviços Agrícolas', whatsapp:'5564999999999', city:'Rio Verde', state:'GO', service_radius_km:120, provider_type:'dono de máquina', source:'seed', status:'active'}];
export const sampleMachines: Machine[] = [{id:'maq-1', provider_id:'prov-1', machine_type:'colheitadeira', brand:'John Deere', model:'S780', year:2022, supported_crops:['soja','milho'], base_city:'Rio Verde', base_state:'GO', service_radius_km:150, average_price:650, status:'active', is_featured:true}];
export async function listRequests() { const supabase = getSupabaseServer(); if (!supabase) return sampleRequests; const { data } = await supabase.from('service_requests').select('*, provider_interests(id)').order('created_at',{ascending:false}); return (data as ServiceRequest[] | null) ?? sampleRequests; }
export async function listProviders() { const supabase = getSupabaseServer(); if (!supabase) return sampleProviders; const { data } = await supabase.from('service_providers').select('*, machines(*)').order('created_at',{ascending:false}); return (data as Provider[] | null) ?? sampleProviders; }
export async function listMachines() { const supabase = getSupabaseServer(); if (!supabase) return sampleMachines; const { data } = await supabase.from('machines').select('*, service_providers(*)').order('created_at',{ascending:false}); return (data as Machine[] | null) ?? sampleMachines; }
