create extension if not exists pgcrypto;
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create table if not exists producers (id uuid primary key default gen_random_uuid(), user_id uuid null, name text not null, company_name text null, whatsapp text not null unique, email text null, country text default 'BR', state text, city text, farm_region text null, main_crops text[] default '{}', estimated_area numeric null, area_unit text default 'ha', source text default 'public_form', status text default 'lead', notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists service_providers (id uuid primary key default gen_random_uuid(), user_id uuid null, name text not null, company_name text null, whatsapp text not null unique, email text null, document text null, country text default 'BR', state text, city text, base_location text null, service_radius_km integer default 100, provider_type text null, source text default 'public_form', status text default 'pending', verified_at timestamptz null, notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists machines (id uuid primary key default gen_random_uuid(), provider_id uuid references service_providers(id) on delete cascade, machine_type text not null, brand text null, model text null, year integer null, platform_width text null, supported_crops text[] default '{}', available_from date null, available_until date null, base_city text null, base_state text null, service_radius_km integer null, average_price numeric null, price_unit text null, status text default 'pending', is_featured boolean default false, notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists service_requests (id uuid primary key default gen_random_uuid(), producer_id uuid references producers(id) null, producer_name text not null, producer_whatsapp text not null, company_name text null, country text default 'BR', state text, city text, farm_region text null, service_type text not null, crop text null, area_amount numeric null, area_unit text default 'ha', expected_start_date date null, urgency text default 'normal', approximate_location text null, notes text null, status text default 'novo', source text default 'public_form', assigned_provider_id uuid null references service_providers(id), assigned_machine_id uuid null references machines(id), estimated_value numeric null, platform_commission numeric null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists provider_interests (id uuid primary key default gen_random_uuid(), service_request_id uuid references service_requests(id) on delete cascade, provider_id uuid references service_providers(id) on delete cascade, machine_id uuid references machines(id) null, message text null, proposed_value numeric null, status text default 'interessado', created_at timestamptz default now(), updated_at timestamptz default now(), unique(service_request_id, provider_id, machine_id));
create table if not exists negotiations (id uuid primary key default gen_random_uuid(), service_request_id uuid references service_requests(id), producer_id uuid references producers(id) null, provider_id uuid references service_providers(id) null, machine_id uuid references machines(id) null, status text default 'aberta', agreed_value numeric null, platform_commission numeric null, notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists quotes (id uuid primary key default gen_random_uuid(), negotiation_id uuid references negotiations(id) null, service_request_id uuid references service_requests(id), provider_id uuid references service_providers(id), machine_id uuid references machines(id) null, amount numeric, price_unit text null, description text null, status text default 'enviado', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists payments (id uuid primary key default gen_random_uuid(), negotiation_id uuid references negotiations(id) null, service_request_id uuid references service_requests(id) null, provider_id uuid references service_providers(id) null, amount numeric, payment_type text null, status text default 'pendente', paid_at timestamptz null, notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists contact_logs (id uuid primary key default gen_random_uuid(), entity_type text not null, entity_id uuid null, contact_type text default 'whatsapp', direction text default 'outbound', message text null, status text null, created_by uuid null, created_at timestamptz default now());
create table if not exists cities (id uuid primary key default gen_random_uuid(), country text default 'BR', state text not null, city text not null, priority integer default 0, is_active boolean default true, notes text null, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists platform_settings (id uuid primary key default gen_random_uuid(), key text unique not null, value jsonb not null default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists idx_service_requests_status_region on service_requests(status, state, city); create index if not exists idx_service_requests_expected_start_date on service_requests(expected_start_date); create index if not exists idx_service_providers_status_region on service_providers(status, state, city); create index if not exists idx_machines_provider_status_type on machines(provider_id, status, machine_type); create index if not exists idx_provider_interests_request_provider on provider_interests(service_request_id, provider_id); create index if not exists idx_producers_whatsapp on producers(whatsapp); create index if not exists idx_service_providers_whatsapp on service_providers(whatsapp);
do $$ declare t text; begin foreach t in array array['producers','service_providers','machines','service_requests','provider_interests','negotiations','quotes','payments','cities','platform_settings'] loop execute format('drop trigger if exists set_%I_updated_at on %I', t, t); execute format('create trigger set_%I_updated_at before update on %I for each row execute function public.set_updated_at()', t, t); end loop; end $$;
insert into cities(state,city,priority) values ('GO','Rio Verde',10),('GO','Jataí',9),('GO','Montividiu',8),('GO','Santa Helena de Goiás',7),('GO','Mineiros',6),('GO','Chapadão do Céu',5),('GO','Quirinópolis',4),('GO','Paraúna',3),('GO','Caiapônia',2),('GO','Santo Antônio da Barra',1) on conflict do nothing;
insert into platform_settings(key,value) values ('default_config','{"currency":"BRL","country":"BR","area_unit":"ha","commission_percent":5}'::jsonb) on conflict (key) do update set value=excluded.value;
-- RLS intentionally disabled for V1 MVP public forms. Enable policies after Supabase Auth/admin roles are configured.
